FROM node:18-alpine

ARG NODE_ENV
ARG MONGODB_URI
ARG PORT
ARG JWT_SECRET
ARG SMTP_USER
ARG SMTP_USERNAME
ARG SMTP_PASSWORD
ARG URL
ARG APP_NAME
ARG CLOUDINARY_NAME
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET

ENV NODE_ENV=${NODE_ENV}
ENV MONGODB_URI=${MONGODB_URI}
ENV PORT=${PORT}
ENV JWT_SECRET=${JWT_SECRET}
ENV SMTP_USER=${SMTP_USER}
ENV SMTP_USERNAME=${SMTP_USERNAME}
ENV SMTP_PASSWORD=${SMTP_PASSWORD}
ENV URL=${URL}
ENV APP_NAME=${APP_NAME}
ENV CLOUDINARY_NAME=${CLOUDINARY_NAME}
ENV CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
ENV CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

WORKDIR /usr
COPY package*.json ./
COPY tsconfig.json ./
COPY src ./src
COPY views ./views
RUN npm install
RUN npm run build

FROM node:18-alpine
WORKDIR /usr
COPY package*.json ./
COPY views ./views
RUN npm install --only=production
COPY --from=0 /usr/dist .

EXPOSE 2003
CMD ["node", "server.js"]