export const APP_NAME = process.env.APP_NAME!
export const MAX_FLOOR = 4
export const MAX_ROW = 12
export const MAX_BOOK_QUANTITY = 100
export const POINT_RANKING = 1000
export const BRONZE_REACH_POINT = 1000,
    SILVER_REACH_POINT = 2000,
    GOLD_REACH_POINT = 4000,
    PLATINUM_REACH_POINT = 6000
